### ISSUE TITLE
Use hypermedia

### ISSUE THREAD

**Issue by pietrodn** [middleware2016/board-rest#1]
In the server responses, hypermedia links to the relevant actions should be included to help the user to navigate the application.

**Comment by carduz** [comment]
Use "options" to retrieve http verbs available

**Comment by carduz** [comment]
app.options('/users', (req, res)=>{
    res.send('GET, POST');
});

**Comment by carduz** [comment]
How do we put search(s)  in hypermedia?

**Comment by pietrodn** [comment]
I've done a first attempt by adding a new "links" virtual attribute in the model. See if you like it!

**Comment by giuanbalina** [comment]
In Play, couldn't we add the link to the winner of the game if present?

**Comment by pietrodn** [comment]
Yes. We should take care that the winner of the game is inside the "additional attributes" and as such it's optional.

**Comment by pietrodn** [comment]
Solved.
