### ISSUE TITLE
tests to do

### ISSUE THREAD

**Issue by carduz** [middleware2016/board-rest#6]
- [x] normal user tries to create a play of another user Expect 403
- [x] power user tries to create a play of another user Expect 201
- [x] normal user tries to create a play of his user Expect 201
- [x] normal user tries to modify profile of another user Expect 403
- [x] power user tries to modify profile of another user Expect 200
- [x] normal user tries to modify profile of his user inserting role parameter Expect 403
- [x] power user tries to modify profile of a user inserting role parameter Expect 200
- [x] normal user tries to modify profile of his user without inserting role parameter Expect 200
- [x] power user tries to modify profile of a user without inserting role parameter Expect 200
- [x] normal user tries to delete profile of his user Expect 200
- [x] power user tries to delete profile of a user Expect 200
- [x] normal user tries to add a game Expect 403
- [x] power user tries to add a game Expect 200
- [x] normal user with a token of deleted user tries to do something where login is required Expect 401
- [x] normal user with an expired token tries to do something where login is required Expect 401
- [x] normal user with a non valid token tries to do something where login is required Expect 401
- [x] OPTIONS for games, users, and plays

**Comment by pietrodn** [comment]
How do I test expired or invalid tokens? @carduz

**Comment by pietrodn** [comment]
All done!
